apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o8pato28i-java-quarkus 
  janus-idp.io/tekton: o8pato28i-java-quarkus
  backstage.io/kubernetes-id: o8pato28i-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o8pato28i-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  